title: Bulus Umoru
subtitle: "Data Analyst | Analytics & Insights"
description: "Data-driven insights and analytical solutions"
url: "https://umorubulus.github.io"
baseurl: "/Portfolio"
logo: github_portfolio.jpg

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

